# Generated by Django 3.2 on 2024-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('files', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'DownloadModel',
            },
        ),
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('keyword1', models.CharField(max_length=100)),
                ('keyword2', models.CharField(max_length=100)),
                ('keyword3', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='static\\Files')),
                ('filename', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'FileUploadModel',
            },
        ),
        migrations.CreateModel(
            name='OwnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OwnersModel',
            },
        ),
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('keyword', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(default='waiting', max_length=100)),
                ('filerequest', models.CharField(default='not requested', max_length=100)),
                ('files', models.FileField(null=True, upload_to='static\\RequestedFiles')),
            ],
            options={
                'db_table': 'SearchModel',
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
            ],
            options={
                'db_table': 'UsersModel',
            },
        ),
    ]
